---
- hosts: rservers
  become: yes

  tasks:
    - name: install system packages, including pre-requisite
      include: tasks/install_host_package.yml
      tags:
        - system_packages

    - name: Install cran packages
      include: tasks/install-r-packages.yml
      tags:
        - cran_packages
