---
# This playbook handles preparing the system for user install of dropbox

- name: dropbox pre-requisites
  apt: 
    name: ['libglapi-mesa', 'libxcb-glx0', 'libxcb-dri2-0', 'libxcb-dri3-0', 'libxcb-present0', 'libxcb-sync1', 'libxshmfence1', 'libxxf86vm1']
    state: present

- name: copy the installation script
  copy:
    src: files/install-dropbox.sh
    dest: /usr/local/bin/install
    mode: 0755
