---
- name: Add the APT key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: Add APT repository
  apt_repository:
    repo: "deb https://cran.rstudio.com/bin/linux/ubuntu/ {{ ansible_distribution_release }}-cran40/"
    mode: 644
    state: present

- name: Install R
  apt:
    name: r-base
    update_cache: yes
