# Ensure all authorised users have a home directory on the server
- name: Make sure all authorised users have a home directory
  shell: mkhomedir_helper "{{ item }}" 0077
  with_items: "{{ authorised_users }}"
  when: authorised_users is defined

# Pdrive when pam_mount is requested
- name: Creating Pdrives
  template:
    src: pam_mount.conf.xml.j2
    dest: /home/"{{ item }}"/.config/pam_mount.conf.xml
    owner: "{{ item }}"
    group: 1000002
    mode: 0644
  with_items: "{{ authorised_users }}"
  when: authorised_users is defined and install_pam_mount
